# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\user\OneDrive\Documents\GitHub\AvisaAi-POO-APS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\user\OneDrive\Documents\GitHub\AvisaAi-POO-APS

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\user\OneDrive\Documents\GitHub\AvisaAi-POO-APS\CMakeFiles D:\user\OneDrive\Documents\GitHub\AvisaAi-POO-APS\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\user\OneDrive\Documents\GitHub\AvisaAi-POO-APS\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AVISAAI

# Build rule for target.
AVISAAI: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 AVISAAI
.PHONY : AVISAAI

# fast build rule for target.
AVISAAI/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/build
.PHONY : AVISAAI/fast

src/Cliente.obj: src/Cliente.cpp.obj
.PHONY : src/Cliente.obj

# target to build an object file
src/Cliente.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/src/Cliente.cpp.obj
.PHONY : src/Cliente.cpp.obj

src/Cliente.i: src/Cliente.cpp.i
.PHONY : src/Cliente.i

# target to preprocess a source file
src/Cliente.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/src/Cliente.cpp.i
.PHONY : src/Cliente.cpp.i

src/Cliente.s: src/Cliente.cpp.s
.PHONY : src/Cliente.s

# target to generate assembly for a file
src/Cliente.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/src/Cliente.cpp.s
.PHONY : src/Cliente.cpp.s

src/ClienteDao.obj: src/ClienteDao.cpp.obj
.PHONY : src/ClienteDao.obj

# target to build an object file
src/ClienteDao.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/src/ClienteDao.cpp.obj
.PHONY : src/ClienteDao.cpp.obj

src/ClienteDao.i: src/ClienteDao.cpp.i
.PHONY : src/ClienteDao.i

# target to preprocess a source file
src/ClienteDao.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/src/ClienteDao.cpp.i
.PHONY : src/ClienteDao.cpp.i

src/ClienteDao.s: src/ClienteDao.cpp.s
.PHONY : src/ClienteDao.s

# target to generate assembly for a file
src/ClienteDao.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/src/ClienteDao.cpp.s
.PHONY : src/ClienteDao.cpp.s

src/ClienteDvo.obj: src/ClienteDvo.cpp.obj
.PHONY : src/ClienteDvo.obj

# target to build an object file
src/ClienteDvo.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/src/ClienteDvo.cpp.obj
.PHONY : src/ClienteDvo.cpp.obj

src/ClienteDvo.i: src/ClienteDvo.cpp.i
.PHONY : src/ClienteDvo.i

# target to preprocess a source file
src/ClienteDvo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/src/ClienteDvo.cpp.i
.PHONY : src/ClienteDvo.cpp.i

src/ClienteDvo.s: src/ClienteDvo.cpp.s
.PHONY : src/ClienteDvo.s

# target to generate assembly for a file
src/ClienteDvo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/src/ClienteDvo.cpp.s
.PHONY : src/ClienteDvo.cpp.s

src/ClienteManager.obj: src/ClienteManager.cpp.obj
.PHONY : src/ClienteManager.obj

# target to build an object file
src/ClienteManager.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/src/ClienteManager.cpp.obj
.PHONY : src/ClienteManager.cpp.obj

src/ClienteManager.i: src/ClienteManager.cpp.i
.PHONY : src/ClienteManager.i

# target to preprocess a source file
src/ClienteManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/src/ClienteManager.cpp.i
.PHONY : src/ClienteManager.cpp.i

src/ClienteManager.s: src/ClienteManager.cpp.s
.PHONY : src/ClienteManager.s

# target to generate assembly for a file
src/ClienteManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/src/ClienteManager.cpp.s
.PHONY : src/ClienteManager.cpp.s

src/DaoManager.obj: src/DaoManager.cpp.obj
.PHONY : src/DaoManager.obj

# target to build an object file
src/DaoManager.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/src/DaoManager.cpp.obj
.PHONY : src/DaoManager.cpp.obj

src/DaoManager.i: src/DaoManager.cpp.i
.PHONY : src/DaoManager.i

# target to preprocess a source file
src/DaoManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/src/DaoManager.cpp.i
.PHONY : src/DaoManager.cpp.i

src/DaoManager.s: src/DaoManager.cpp.s
.PHONY : src/DaoManager.s

# target to generate assembly for a file
src/DaoManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/src/DaoManager.cpp.s
.PHONY : src/DaoManager.cpp.s

src/DvoManager.obj: src/DvoManager.cpp.obj
.PHONY : src/DvoManager.obj

# target to build an object file
src/DvoManager.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/src/DvoManager.cpp.obj
.PHONY : src/DvoManager.cpp.obj

src/DvoManager.i: src/DvoManager.cpp.i
.PHONY : src/DvoManager.i

# target to preprocess a source file
src/DvoManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/src/DvoManager.cpp.i
.PHONY : src/DvoManager.cpp.i

src/DvoManager.s: src/DvoManager.cpp.s
.PHONY : src/DvoManager.s

# target to generate assembly for a file
src/DvoManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/src/DvoManager.cpp.s
.PHONY : src/DvoManager.cpp.s

src/Pagamento.obj: src/Pagamento.cpp.obj
.PHONY : src/Pagamento.obj

# target to build an object file
src/Pagamento.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/src/Pagamento.cpp.obj
.PHONY : src/Pagamento.cpp.obj

src/Pagamento.i: src/Pagamento.cpp.i
.PHONY : src/Pagamento.i

# target to preprocess a source file
src/Pagamento.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/src/Pagamento.cpp.i
.PHONY : src/Pagamento.cpp.i

src/Pagamento.s: src/Pagamento.cpp.s
.PHONY : src/Pagamento.s

# target to generate assembly for a file
src/Pagamento.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/src/Pagamento.cpp.s
.PHONY : src/Pagamento.cpp.s

src/PagamentoDao.obj: src/PagamentoDao.cpp.obj
.PHONY : src/PagamentoDao.obj

# target to build an object file
src/PagamentoDao.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/src/PagamentoDao.cpp.obj
.PHONY : src/PagamentoDao.cpp.obj

src/PagamentoDao.i: src/PagamentoDao.cpp.i
.PHONY : src/PagamentoDao.i

# target to preprocess a source file
src/PagamentoDao.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/src/PagamentoDao.cpp.i
.PHONY : src/PagamentoDao.cpp.i

src/PagamentoDao.s: src/PagamentoDao.cpp.s
.PHONY : src/PagamentoDao.s

# target to generate assembly for a file
src/PagamentoDao.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/src/PagamentoDao.cpp.s
.PHONY : src/PagamentoDao.cpp.s

src/PagamentoManager.obj: src/PagamentoManager.cpp.obj
.PHONY : src/PagamentoManager.obj

# target to build an object file
src/PagamentoManager.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/src/PagamentoManager.cpp.obj
.PHONY : src/PagamentoManager.cpp.obj

src/PagamentoManager.i: src/PagamentoManager.cpp.i
.PHONY : src/PagamentoManager.i

# target to preprocess a source file
src/PagamentoManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/src/PagamentoManager.cpp.i
.PHONY : src/PagamentoManager.cpp.i

src/PagamentoManager.s: src/PagamentoManager.cpp.s
.PHONY : src/PagamentoManager.s

# target to generate assembly for a file
src/PagamentoManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/src/PagamentoManager.cpp.s
.PHONY : src/PagamentoManager.cpp.s

src/Pedido.obj: src/Pedido.cpp.obj
.PHONY : src/Pedido.obj

# target to build an object file
src/Pedido.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/src/Pedido.cpp.obj
.PHONY : src/Pedido.cpp.obj

src/Pedido.i: src/Pedido.cpp.i
.PHONY : src/Pedido.i

# target to preprocess a source file
src/Pedido.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/src/Pedido.cpp.i
.PHONY : src/Pedido.cpp.i

src/Pedido.s: src/Pedido.cpp.s
.PHONY : src/Pedido.s

# target to generate assembly for a file
src/Pedido.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/src/Pedido.cpp.s
.PHONY : src/Pedido.cpp.s

src/PedidoDao.obj: src/PedidoDao.cpp.obj
.PHONY : src/PedidoDao.obj

# target to build an object file
src/PedidoDao.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/src/PedidoDao.cpp.obj
.PHONY : src/PedidoDao.cpp.obj

src/PedidoDao.i: src/PedidoDao.cpp.i
.PHONY : src/PedidoDao.i

# target to preprocess a source file
src/PedidoDao.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/src/PedidoDao.cpp.i
.PHONY : src/PedidoDao.cpp.i

src/PedidoDao.s: src/PedidoDao.cpp.s
.PHONY : src/PedidoDao.s

# target to generate assembly for a file
src/PedidoDao.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/src/PedidoDao.cpp.s
.PHONY : src/PedidoDao.cpp.s

src/PedidoDvo.obj: src/PedidoDvo.cpp.obj
.PHONY : src/PedidoDvo.obj

# target to build an object file
src/PedidoDvo.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/src/PedidoDvo.cpp.obj
.PHONY : src/PedidoDvo.cpp.obj

src/PedidoDvo.i: src/PedidoDvo.cpp.i
.PHONY : src/PedidoDvo.i

# target to preprocess a source file
src/PedidoDvo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/src/PedidoDvo.cpp.i
.PHONY : src/PedidoDvo.cpp.i

src/PedidoDvo.s: src/PedidoDvo.cpp.s
.PHONY : src/PedidoDvo.s

# target to generate assembly for a file
src/PedidoDvo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/src/PedidoDvo.cpp.s
.PHONY : src/PedidoDvo.cpp.s

src/PedidoManager.obj: src/PedidoManager.cpp.obj
.PHONY : src/PedidoManager.obj

# target to build an object file
src/PedidoManager.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/src/PedidoManager.cpp.obj
.PHONY : src/PedidoManager.cpp.obj

src/PedidoManager.i: src/PedidoManager.cpp.i
.PHONY : src/PedidoManager.i

# target to preprocess a source file
src/PedidoManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/src/PedidoManager.cpp.i
.PHONY : src/PedidoManager.cpp.i

src/PedidoManager.s: src/PedidoManager.cpp.s
.PHONY : src/PedidoManager.s

# target to generate assembly for a file
src/PedidoManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/src/PedidoManager.cpp.s
.PHONY : src/PedidoManager.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\AVISAAI.dir\build.make CMakeFiles/AVISAAI.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... AVISAAI
	@echo ... src/Cliente.obj
	@echo ... src/Cliente.i
	@echo ... src/Cliente.s
	@echo ... src/ClienteDao.obj
	@echo ... src/ClienteDao.i
	@echo ... src/ClienteDao.s
	@echo ... src/ClienteDvo.obj
	@echo ... src/ClienteDvo.i
	@echo ... src/ClienteDvo.s
	@echo ... src/ClienteManager.obj
	@echo ... src/ClienteManager.i
	@echo ... src/ClienteManager.s
	@echo ... src/DaoManager.obj
	@echo ... src/DaoManager.i
	@echo ... src/DaoManager.s
	@echo ... src/DvoManager.obj
	@echo ... src/DvoManager.i
	@echo ... src/DvoManager.s
	@echo ... src/Pagamento.obj
	@echo ... src/Pagamento.i
	@echo ... src/Pagamento.s
	@echo ... src/PagamentoDao.obj
	@echo ... src/PagamentoDao.i
	@echo ... src/PagamentoDao.s
	@echo ... src/PagamentoManager.obj
	@echo ... src/PagamentoManager.i
	@echo ... src/PagamentoManager.s
	@echo ... src/Pedido.obj
	@echo ... src/Pedido.i
	@echo ... src/Pedido.s
	@echo ... src/PedidoDao.obj
	@echo ... src/PedidoDao.i
	@echo ... src/PedidoDao.s
	@echo ... src/PedidoDvo.obj
	@echo ... src/PedidoDvo.i
	@echo ... src/PedidoDvo.s
	@echo ... src/PedidoManager.obj
	@echo ... src/PedidoManager.i
	@echo ... src/PedidoManager.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

